- !policy
  id: {{ cluster-id }}
  body:
    - !webservice
    
    - !variable jwks-uri
    - !variable issuer
    - !variable token-app-property
    - !variable identity-path
    - !variable audience

    # Group of applications that can authenticate using this JWT Authenticator
    - !group apps

    - !permit
      role: !group apps
      privilege: [ authenticate ]
      resource: !webservice

    - !webservice status

    # Group of users who can check the status of the JWT Authenticator
    - !group operators

    - !permit
      role: !group operators
      privilege: [ read ]
      resource: !webservice status

    - !grant
      role: !group apps
      member: !group /data/apps/authenticators
