---
apiVersion: v1
kind: Service
metadata:
  name: onboarding
spec:
  type: LoadBalancer
  selector:
    app: onboarding
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: on-svc-port
    - protocol: TCP
      name: http
      port: 80
      targetPort: hc-svc-port